<a href="https://colab.research.google.com/github/nitpat25/Object-Detection/blob/main/tensorflow_basics_part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
tensor_zero_d = tf.constant(4) # zero dimensional tensor
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_zero_d

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [ ]:
tensor_one_d = tf.constant([2,0,-3]) # one dimensional tensor
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2,0,-3,1,3,3,3]) # one dimensional tensor
print(tensor_one_d)

tf.Tensor([ 2  0 -3  1  3  3  3], shape=(7,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([[1,2,0],[3,5,-1],[1,5,6],[2,3,8]])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([[[1,2,0],[3,5,-1]],
[[10,4,2],[1,0,5]],
[[5,3,1],[6,7,4]],
[[7,5,1],[0,7,5]]])
print(tensor_three_d) # 4 rows, each row has 2 sub rows, there are 3 columns

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  4  2]
  [ 1  0  5]]

 [[ 5  3  1]
  [ 6  7  4]]

 [[ 7  5  1]
  [ 0  7  5]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
tensor_three_d.shape

TensorShape([4, 2, 3])

In [ ]:
tensor_bool = tf.constant([True,True,False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [ ]:
tensor_string = tf.constant(["Hello World","Hi"])
print(tensor_string)

tf.Tensor([b'Hello World' b'Hi'], shape=(2,), dtype=string)


In [ ]:
import numpy as np

In [ ]:
np_array = np.array([1,2,4])
np_array

array([1, 2, 4])

In [ ]:
converted_tensor = tf.convert_to_tensor(np_array)
converted_tensor

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 4])>

In [ ]:
eye_tensor = tf.eye(num_rows = 3,
                    num_columns = None,
                    batch_shape = None,
                    dtype = tf.dtypes.float32,
                    name = None)
print(eye_tensor)
print(3*eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)


In [ ]:
eye_tensor = tf.eye(num_rows = 3,
                    num_columns = None,
                    batch_shape = None,
                    dtype = tf.dtypes.bool,
                    name = None)
print(eye_tensor)

tf.Tensor(
[[ True False False]
 [False  True False]
 [False False  True]], shape=(3, 3), dtype=bool)


In [ ]:
eye_tensor = tf.eye(num_rows = 5,
                    num_columns = 3,
                    batch_shape = None,
                    dtype = tf.dtypes.float32,
                    name = None)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(5, 3), dtype=float32)


In [ ]:
eye_tensor = tf.eye(num_rows = 3,
                    num_columns = 5,
                    batch_shape = None,
                    dtype = tf.dtypes.float32,
                    name = None)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]], shape=(3, 5), dtype=float32)


In [ ]:
eye_tensor = tf.eye(num_rows = 5,
                    num_columns = 5,
                    batch_shape = [5,],
                    dtype = tf.dtypes.float32,
                    name = None)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(5, 5, 5), dtype=float32)


In [ ]:
eye_tensor = tf.eye(num_rows = 5,
                    num_columns = 5,
                    batch_shape = [2,],
                    dtype = tf.dtypes.float32,
                    name = None)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(2, 5, 5), dtype=float32)


In [ ]:
eye_tensor = tf.eye(num_rows = 5,
                    num_columns = 5,
                    batch_shape = [2,2],
                    dtype = tf.dtypes.float32,
                    name = None)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]], shape=(2, 2, 5, 5), dtype=float32)


In [ ]:
fill_tensor = tf.fill([2,3,4],5, name = None) # 3D Tensor
print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(2, 3, 4), dtype=int32)


In [ ]:
ones_tensor = tf.ones([2,5,3],dtype = tf.dtypes.float32,name=None)
print(ones_tensor)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 5, 3), dtype=float32)


In [ ]:
ones_like_tensor = tf.ones_like(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(2, 3, 4), dtype=int32)


In [ ]:
zeros_tensor = tf.zeros(
    [3,2],
    dtype = tf.dtypes.float32,
    name = None
)
print(zeros_tensor)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [ ]:
zeros_like_tensor = tf.zeros_like(fill_tensor)
print(zeros_like_tensor)

tf.Tensor(
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]], shape=(2, 3, 4), dtype=int32)


In [ ]:
print(zeros_like_tensor.ndim)

3


In [ ]:
print(zeros_like_tensor.shape)

(2, 3, 4)


In [ ]:
print(tf.shape(zeros_like_tensor))

tf.Tensor([2 3 4], shape=(3,), dtype=int32)


In [ ]:
t = tf.constant([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]]) # 0-D tensor
print(tf.shape(t))
tf.rank(t)

tf.Tensor([2 2 3], shape=(3,), dtype=int32)


<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
t = tf.constant([[1,1,1],[2,2,2]]) # 0-D tensor
print(tf.shape(t))
tf.rank(t)

tf.Tensor([2 3], shape=(2,), dtype=int32)


<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
t = tf.constant([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
tf.size(t)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [ ]:
t = tf.constant([[[1,1,1],[2,2,2]]])
tf.size(t,out_type=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [ ]:
random_tensor = tf.random.normal(
    [3,2],
    mean = 0.0,
    stddev = 1.0,
    dtype = tf.dtypes.float32,
    seed = None,
    name = None
)
print(random_tensor)

tf.Tensor(
[[ 0.28145745 -0.76462936]
 [-0.7964535  -0.09085122]
 [-0.683644   -0.8597029 ]], shape=(3, 2), dtype=float32)


In [ ]:
random_tensor = tf.random.uniform(
    [1,],
    minval = 0,
    maxval = None, #default maxval=1
    dtype = tf.dtypes.float32,
    seed = None,
    name = None
)
print(random_tensor)

tf.Tensor([0.47249806], shape=(1,), dtype=float32)


In [ ]:
random_tensor = tf.random.uniform(
    [5,],
    minval = 0,
    maxval = 8,
    dtype = tf.dtypes.float32,
    seed = None,
    name = None
)
print(random_tensor)

tf.Tensor([6.963559  5.622304  3.4514055 6.3585396 3.8615427], shape=(5,), dtype=float32)


In [ ]:
random_tensor = tf.random.uniform(
    [5,],
    minval = 0,
    maxval = None,
    dtype = tf.dtypes.int32,
    seed = None,
    name = None
)
print(random_tensor)

ValueError: ignored

In [ ]:
random_tensor = tf.random.uniform(
    [5,5],
    minval = 0,
    maxval = 1000,
    dtype = tf.dtypes.int32,
    seed = None,
    name = None
)
print(random_tensor)

tf.Tensor(
[[  6 702 748 518 874]
 [146 836 702 826 507]
 [638  33 371 384 627]
 [867 227 615 710 226]
 [706 824 545 542 981]], shape=(5, 5), dtype=int32)


In [ ]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [ ]:
tensor_indexed = tf.constant([3,6,2,4,6,66,7])
print(tensor_indexed)

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)


In [ ]:
tensor_indexed = tf.constant([3,6,2,4,6,66,7])
print(tensor_indexed[0:4])
print(tensor_indexed[1:6:2])
print(tensor_indexed[3:-3])

tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 6  4 66], shape=(3,), dtype=int32)
tf.Tensor([4], shape=(1,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([[1,2,0],
                            [3,5,-1],
                            [1,5,6],
                            [2,3,8]])
print(tensor_two_d[0:3,0:2])

tf.Tensor(
[[1 2]
 [3 5]
 [1 5]], shape=(3, 2), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([[1,2,0],
                            [3,5,-1],
                            [1,5,6],
                            [2,3,8]])
print(tensor_two_d[2:3,:])

tf.Tensor([[1 5 6]], shape=(1, 3), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([[1,2,0],
                            [3,5,-1],
                            [1,5,6],
                            [2,3,8]])
print(tensor_two_d[2,0])

tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([[1,2,0],
                            [3,5,-1],
                            [1,5,6],
                            [2,3,8]])
print(tensor_two_d[...,1])

tf.Tensor([2 5 5 3], shape=(4,), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([[[1,2,0],[3,5,-1]],
[[10,4,2],[1,0,5]],
[[5,3,1],[6,7,4]],
[[7,5,1],[0,7,5]]])
print(tensor_three_d[0,:,-1])

tf.Tensor([ 0 -1], shape=(2,), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([[[1,2,0],[3,5,-1]],
[[10,4,2],[1,0,5]],
[[5,3,1],[6,7,4]],
[[7,5,1],[0,7,5]]])
print(tensor_three_d[...,:,2])

tf.Tensor(
[[ 0 -1]
 [ 2  5]
 [ 1  4]
 [ 1  5]], shape=(4, 2), dtype=int32)


In [ ]:
x_abs = tf.constant([-2.25,3.25])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [ ]:
x_abs_complex = tf.constant([-2.25+3.25j])
tf.abs(x_abs_complex)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([3.95284708])>

In [ ]:
tf.sqrt((-2.25)**2+3.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=4.373214>

In [ ]:
x_1 = tf.constant([3,6,2,4,6,66,7])
x_2 = tf.constant([1,4,21,44,6,46,70])
print(tf.add(x_1,x_2))

tf.Tensor([  4  10  23  48  12 112  77], shape=(7,), dtype=int32)


In [ ]:
x_1 = tf.constant([3,6,2,4,6,66,7])
x_2 = tf.constant([1,4,21,44,6,46,70])
print(tf.subtract(x_1,x_2))

tf.Tensor([  2   2 -19 -40   0  20 -63], shape=(7,), dtype=int32)


In [ ]:
x_1 = tf.constant([3,6,2,4,6,66,7])
x_2 = tf.constant([1,4,21,44,6,46,70])
print(tf.multiply(x_1,x_2))

tf.Tensor([   3   24   42  176   36 3036  490], shape=(7,), dtype=int32)


In [ ]:
x_1 = tf.constant([3,6,1,4,6,66,7],dtype = tf.float32)
x_2 = tf.constant([1,4,0,44,6,46,70],dtype = tf.float32)
print(tf.math.divide_no_nan(x_1,x_2))

tf.Tensor(
[3.         1.5        0.         0.09090909 1.         1.4347826
 0.1       ], shape=(7,), dtype=float32)


In [ ]:
x_1 = tf.constant([3,6,1,4,6,66,7],dtype = tf.float32)
x_2 = tf.constant([1,4,0,44,6,46,70],dtype = tf.float32)
print(tf.divide(x_1,x_2))

tf.Tensor(
[3.         1.5               inf 0.09090909 1.         1.4347826
 0.1       ], shape=(7,), dtype=float32)


In [ ]:
x_1 = tf.constant([[5,3,6,6,4,6]])
x_2 = tf.constant([[7],[5],[3]])
print(x_1.shape)
print(x_2.shape)
print(tf.multiply(x_1,x_2))

(1, 6)
(3, 1)
tf.Tensor(
[[35 21 42 42 28 42]
 [25 15 30 30 20 30]
 [15  9 18 18 12 18]], shape=(3, 6), dtype=int32)


In [ ]:
x_argmax = tf.constant([5,3,6,6,4,6]) # index of max value
print(tf.math.argmax(x_argmax))

tf.Tensor(2, shape=(), dtype=int64)


In [ ]:
x_argmax = tf.constant([[35, 21, 42, 42, 28, 42],
                        [25, 15, 30, 30, 20, 30],
                        [15,  9, 18, 100000, 12, 18]])
print(tf.math.argmax(x_argmax, 0))

tf.Tensor([0 0 0 2 0 0], shape=(6,), dtype=int64)


In [ ]:
x_argmax = tf.constant([[35, 21, 42, 42, 28, 42],
                        [25, 15, 30, 30, 20, 30],
                        [15,  9, 18, 100000, 12, 18]])
print(tf.math.argmax(x_argmax, 1))

tf.Tensor([2 2 3], shape=(3,), dtype=int64)


In [ ]:
x_argmin = tf.constant([[35, 21, 42, 42, 28, 42],
                        [25, 15, 30, 30, 20, 30],
                        [15,  9, 18, 100000, 12, 18]])
print(tf.math.argmin(x_argmin, 1))

tf.Tensor([1 1 1], shape=(3,), dtype=int64)


In [ ]:
tf.pow(tf.constant(2),tf.constant(3))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [ ]:
x = tf.constant([[2,2],[3,3]])
y = tf.constant([[3,0],[1,4]])
tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 8,  1],
       [ 3, 81]], dtype=int32)>

In [ ]:
x = tf.constant([[2,2],[3,3]])
print(tf.math.reduce_sum(x,axis = None,keepdims=False,name=None))

tf.Tensor(10, shape=(), dtype=int32)


In [ ]:
x = tf.constant([2,2])
print(tf.math.reduce_sum(x,axis = None,keepdims=False,name=None))

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
x = tf.constant([[2,2],[3,1]])
print(tf.math.reduce_sum(x,axis = None,keepdims=False,name=None))

tf.Tensor(8, shape=(), dtype=int32)


In [ ]:
x = tf.constant([[2,2],[3,1]])
print(tf.math.reduce_max(x,axis = None,keepdims=False,name=None))

tf.Tensor(3, shape=(), dtype=int32)


In [ ]:
x = tf.constant([[2,2],[3,1]])
print(tf.math.reduce_min(x,axis = None,keepdims=False,name=None))

tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
x = tf.constant([[2,2],[3,1]])
print(tf.math.reduce_sum(x,axis = 0,keepdims=False,name=None))

tf.Tensor([5 3], shape=(2,), dtype=int32)


In [ ]:
x = tf.constant([[2,2],[3,1]])
print(tf.math.reduce_sum(x,axis = 1,keepdims=False,name=None))

tf.Tensor([4 4], shape=(2,), dtype=int32)


In [ ]:
x = tf.constant([[2,2],[3,1]],dtype = tf.float16)
print(tf.math.reduce_mean(x,axis = 0,keepdims=False,name=None))

tf.Tensor([2.5 1.5], shape=(2,), dtype=float16)


In [ ]:
x = tf.constant([[2,2],[3,1]],dtype = tf.float16)
print(tf.math.reduce_mean(x,axis = 1,keepdims=False,name=None))

tf.Tensor([2. 2.], shape=(2,), dtype=float16)


In [ ]:
x = tf.constant([[2,2],[3,1]],dtype = tf.float16)
print(tf.math.reduce_std(x,axis = 0,keepdims=False,name=None))

tf.Tensor([0.5 0.5], shape=(2,), dtype=float16)


In [ ]:
x = tf.constant([[2,2],[3,1]],dtype = tf.float16)
print(tf.math.reduce_std(x,axis = 1,keepdims=True,name=None))

tf.Tensor(
[[0.]
 [1.]], shape=(2, 1), dtype=float16)


In [ ]:
tf.math.top_k(x,k=2)

TopKV2(values=<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[2., 2.],
       [3., 1.]], dtype=float16)>, indices=<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 1],
       [0, 1]], dtype=int32)>)

In [ ]:
x_1  =tf.constant([[1,2,0]])
x_2 = tf.constant([[1,2,0,2],
                   [3,5,-1,2],
                   [4,5,6,0]])
tf.linalg.matmul(
    x_1,x_2,transpose_a=False,transpose_b=False,adjoint_a=False,adjoint_b=False,a_is_sparse=False,b_is_sparse=False,output_type = None,name=None
)

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[ 7, 12, -2,  6]], dtype=int32)>

In [ ]:
print(x_1@x_2)

tf.Tensor([[ 7 12 -2  6]], shape=(1, 4), dtype=int32)


In [ ]:
x_1  =tf.constant([[1,2,0]]) # Element-wise multipliciation
x_2 = tf.constant([[1,2,0]])
tf.math.multiply(x_1,x_2)

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 4, 0]], dtype=int32)>

In [ ]:
print(x_1*x_2)

tf.Tensor([[1 4 0]], shape=(1, 3), dtype=int32)


In [ ]:
tf.transpose(x_1)

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [0]], dtype=int32)>

In [ ]:
tf.transpose(x_2)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  3,  4],
       [ 2,  5,  5],
       [ 0, -1,  6],
       [ 2,  2,  0]], dtype=int32)>

In [ ]:
l = [1,3,2]
l.sort()
l

[1, 2, 3]

In [ ]:
l[1:-1]

[2]

In [ ]:
l[-1]

3